trigger:
  - master
  
pool:
  vmImage: 'ubuntu-latest'

stages:
  
- stage: buildDeploy
  displayName: 'Build / Deploy'
  jobs:
    - job: runDeploymnet
      displayName: 'Run Deployment'
      steps:
        - script: 'echo deploying...'

- stage: test
  displayName: 'Test'
  dependsOn: buildDeploy
  jobs:
  - job: runLighthouse
    displayName: 'Run Lighthouse'
    variables:
      LHCI_BUILD_CONTEXT__CURRENT_BRANCH: '$(Build.SourceBranch)'
    steps:
      - checkout: 'self'
        fetchDepth: 1

      - task: Npm@1
        inputs:
          command: 'install'

      - task: Npm@1
        displayName: 'Healthcheck'
        inputs:
          command: 'custom'
          customCommand: 'run lighthouse:healthcheck'

      - task: Npm@1
        displayName: 'Collect'
        inputs:
          command: 'custom'
          customCommand: 'run lighthouse:collect'

      - task: Npm@1
        displayName: 'Assert'
        inputs:
          command: 'custom'
          customCommand: 'run lighthouse:assert'

      - task: Npm@1
        displayName: 'Upload'
        inputs:
          command: 'custom'
          customCommand: 'run lighthouse:upload'

- stage: release
  displayName: 'Release'
  dependsOn: test
  jobs:
    - job: runRelease
      displayName: 'Run Release'
      steps:
        - script: 'echo releasing...'